import SwiftUI

// MARK: - Data (Shared/forms.json, generated by tools/forms/forms.py)

struct FormPrim: Decodable {
    let k: String
    let p: [[Double]]
    let w: Double
}

enum FormAnchor: Decodable {
    case foot, hands, point(Double, Double, Double?)

    init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if let s = try? c.decode(String.self) {
            self = s == "foot" ? .foot : .hands
            return
        }
        let arr = try c.decode([Double?].self)
        self = .point(arr.first.flatMap { $0 } ?? 0, arr.count > 1 ? (arr[1] ?? 0) : 0, arr.count > 2 ? arr[2] : nil)
    }
}

struct FormImplement: Decodable {
    let t: String
    let hands: String
    let anchor: FormAnchor?
    let at: String
}

struct FormPattern: Decodable {
    let view: String
    let T: Double
    let cx: Double
    let f: [[Double]]
    let pr: [FormPrim]
    /// Looping patterns (walking, running, elliptical) play straight through instead of back and forth.
    let loop: Bool?

    func frame(at t: Double) -> [Double] {
        let n = f.count
        guard n > 1 else { return f.first ?? [] }
        let fi = max(0, min(1, t)) * Double(n - 1)
        let i0 = Int(fi.rounded(.down))
        let i1 = min(i0 + 1, n - 1)
        let k = fi - Double(i0)
        let a = f[i0], b = f[i1]
        var out = a
        for i in out.indices { out[i] = a[i] + (b[i] - a[i]) * k }
        return out
    }

    /// Back-and-forth loop with short pauses at each end.
    func phase(_ time: Double) -> Double {
        let u = time.truncatingRemainder(dividingBy: T) / T
        if loop == true { return u }
        let tri = u < 0.5 ? u * 2 : 2 - u * 2
        let x = max(0, min(1, (tri - 0.08) / 0.84))
        return 0.5 - 0.5 * cos(Double.pi * x)
    }

    /// The angle this pattern is authored from: side (90°) or front (0°).
    var defaultYaw: Double { view == "f" ? 0 : 90 }
}

struct FormExercise: Decodable {
    let p: String
    let i: [FormImplement]
    let x: [FormPrim]
}

struct FormLibraryData: Decodable {
    let ground: Double
    let head: Double
    let patterns: [String: FormPattern]
    let exercises: [String: FormExercise]
    let cues: [String: [String]]
    let tips: [String: String]
}

enum FormLibrary {
    static let shared: FormLibraryData? = {
        guard let url = Bundle.main.url(forResource: "forms", withExtension: "json"),
              let data = try? Data(contentsOf: url) else { return nil }
        return try? JSONDecoder().decode(FormLibraryData.self, from: data)
    }()

    /// The animation to use: the exercise's own, or for a custom exercise the built-in one it moves like.
    static func key(_ exerciseID: String) -> String {
        if shared?.exercises[exerciseID] != nil { return exerciseID }
        return ExerciseLibrary.byID[exerciseID]?.formLike ?? exerciseID
    }

    static func cues(for exerciseID: String) -> [String] {
        guard let lib = shared, let ex = lib.exercises[key(exerciseID)] else { return [] }
        return lib.cues[ex.p] ?? []
    }

    static func tip(for exerciseID: String) -> String? { shared?.tips[exerciseID] }

    static func defaultYaw(for exerciseID: String) -> Double {
        guard let lib = shared, let ex = lib.exercises[key(exerciseID)], let pat = lib.patterns[ex.p] else { return 90 }
        return pat.defaultYaw
    }
}

// MARK: - Scene (same algorithm as tools/forms/forms.py and the preview page)

enum FormRole { case ink, accent, plate, steel, prop, propFill, cable, band, pad, ground, face }

struct FormOp {
    enum Kind { case line, circle, poly }
    var kind: Kind
    var pts: [CGPoint] = []
    var center: CGPoint = .zero
    var rx: Double = 0
    var ry: Double = 0
    var width: Double = 1
    var role: FormRole
    var stroke: FormRole = .prop
    var alpha: Double = 1
    var dashed = false
    var depth: Double = 0
}

enum FormScene {
    static let head = 0, neck = 1, pelvis = 2, nose = 17
    static let arms: [[Int]] = [[3, 4, 5], [6, 7, 8]]
    static let legs: [[Int]] = [[9, 10, 11, 12], [13, 14, 15, 16]]

    typealias V3 = (Double, Double, Double)

    static func ops(pattern pat: FormPattern, exercise ex: FormExercise, frame F: [Double], yaw: Double,
                    ground: Double, headRadius: Double) -> [FormOp] {
        let sinY = sin(yaw), cosY = cos(yaw)
        let cx = pat.cx

        func pt(_ i: Int) -> V3 { (F[i * 3], F[i * 3 + 1], F[i * 3 + 2]) }
        func pr(_ p: V3) -> V3 {
            let dx: Double = p.0 - cx
            let sx: Double = dx * sinY + p.2 * cosY + 50.0
            let depth: Double = dx * cosY - p.2 * sinY
            return (sx, p.1, depth)
        }
        func prA(_ a: [Double]) -> V3 { pr((a[0], a[1], a[2])) }
        func cg(_ v: V3) -> CGPoint { CGPoint(x: v.0, y: v.1) }
        func add(_ a: V3, _ b: V3, _ k: Double = 1) -> V3 {
            let x: Double = a.0 + b.0 * k
            let y: Double = a.1 + b.1 * k
            let z: Double = a.2 + b.2 * k
            return (x, y, z)
        }
        func mid(_ ps: [V3]) -> V3 {
            var x = 0.0, y = 0.0, z = 0.0
            for p in ps { x += p.0; y += p.1; z += p.2 }
            let n = Double(ps.count)
            return (x / n, y / n, z / n)
        }
        func norm(_ v: V3) -> V3 {
            let sq: Double = v.0 * v.0 + v.1 * v.1 + v.2 * v.2
            let m = sq.squareRoot()
            if m <= 0 { return (0, 0, 0) }
            return (v.0 / m, v.1 / m, v.2 / m)
        }
        func avgDepth(_ q: [V3]) -> Double {
            var t = 0.0
            for p in q { t += p.2 }
            return q.isEmpty ? 0 : t / Double(q.count)
        }

        var props: [FormOp] = []
        var items: [FormOp] = []

        for prim in pat.pr + ex.x {
            switch prim.k {
            case "seg":
                let q = prim.p.map { prA($0) }
                props.append(FormOp(kind: .line, pts: q.map(cg), width: prim.w, role: .prop, depth: avgDepth(q)))
            case "poly":
                let q = prim.p.map { prA($0) }
                props.append(FormOp(kind: .poly, pts: q.map(cg), width: prim.w, role: .propFill, stroke: .prop,
                                    depth: avgDepth(q)))
            default:
                guard prim.p.count == 2 else { continue }
                let lo = prim.p[0], hi = prim.p[1]
                var q: [V3] = []
                for x in [lo[0], hi[0]] { for y in [lo[1], hi[1]] { for z in [lo[2], hi[2]] { q.append(pr((x, y, z))) } } }
                props.append(FormOp(kind: .poly, pts: hull(q.map(cg)), width: 0.8, role: .propFill, stroke: .prop,
                                    depth: avgDepth(q)))
            }
        }

        let dT = (pr(pt(neck)).2 + pr(pt(pelvis)).2) / 2
        func alpha(_ d: Double) -> Double {
            let behind: Double = (-2.0 - (d - dT)) / 10.0
            let clamped: Double = Swift.max(0.0, Swift.min(1.0, behind))
            return 1.0 - 0.55 * clamped
        }
        func seg(_ i: Int, _ j: Int, _ w: Double) {
            let a = pr(pt(i)), b = pr(pt(j))
            let d = (a.2 + b.2) / 2
            items.append(FormOp(kind: .line, pts: [cg(a), cg(b)], width: w, role: .ink, alpha: alpha(d), depth: d))
        }
        seg(neck, pelvis, 4.4)
        seg(arms[0][0], arms[1][0], 3.4)
        seg(legs[0][0], legs[1][0], 3.4)
        for a in arms { seg(a[0], a[1], 3.0); seg(a[1], a[2], 2.8) }
        for l in legs { seg(l[0], l[1], 3.4); seg(l[1], l[2], 3.0); seg(l[2], l[3], 2.4) }
        let hp = pr(pt(head))
        items.append(FormOp(kind: .circle, center: cg(hp), rx: headRadius, ry: headRadius, role: .ink, depth: hp.2))
        let np = pr(pt(nose))
        if np.2 > hp.2 - 0.5 {
            items.append(FormOp(kind: .circle, center: cg(np), rx: 1.1, ry: 1.1, role: .face, depth: hp.2 + 0.01))
        }

        let W = [pt(arms[0][2]), pt(arms[1][2])]
        let S = [pt(arms[0][0]), pt(arms[1][0])]
        for im in ex.i {
            let hands: [(V3, Int)]
            switch im.hands {
            case "both": hands = [(W[0], 0), (W[1], 1)]
            case "near": hands = [(W[0], 0)]
            default: hands = [(mid([W[0], W[1]]), 0)]
            }
            switch im.t {
            case "barbell":
                let C = im.hands == "near" ? W[0] : mid([W[0], W[1]])
                let a = pr(add(C, (0, 0, -22))), b = pr(add(C, (0, 0, 22)))
                items.append(FormOp(kind: .line, pts: [cg(a), cg(b)], width: 1.4, role: .steel, depth: (a.2 + b.2) / 2))
                for z in [-18.0, 18.0] {
                    let p = pr(add(C, (0, 0, z)))
                    items.append(FormOp(kind: .circle, center: cg(p), rx: Swift.max(1.1, 7.0 * Swift.abs(sinY)), ry: 7, role: .plate, depth: p.2))
                }
            case "dumbbell":
                for (H, _) in hands {
                    let a = pr(add(H, (0, 0, -3.5))), b = pr(add(H, (0, 0, 3.5)))
                    items.append(FormOp(kind: .line, pts: [cg(a), cg(b)], width: 1.3, role: .steel, depth: (a.2 + b.2) / 2))
                    for p in [a, b] {
                        items.append(FormOp(kind: .circle, center: cg(p), rx: Swift.max(1.0, 3.0 * Swift.abs(sinY)), ry: 3, role: .plate, depth: p.2))
                    }
                }
            case "kettlebell":
                for (H, _) in hands {
                    let a = pr(H), b = pr(add(H, (0, -4.6, 0)))
                    items.append(FormOp(kind: .line, pts: [cg(a), cg(b)], width: 1.2, role: .steel, depth: b.2))
                    items.append(FormOp(kind: .circle, center: cg(b), rx: 3.6, ry: 3.6, role: .plate, depth: b.2 + 0.01))
                }
            case "cable", "band":
                if case .hands? = im.anchor {
                    let a = pr(W[0]), b = pr(W[1])
                    items.append(FormOp(kind: .line, pts: [cg(a), cg(b)], width: 1.1, role: .band, dashed: true, depth: (a.2 + b.2) / 2))
                    continue
                }
                for (H, i) in hands {
                    let A3: V3
                    switch im.anchor {
                    case .some(.point(let x, let y, let out)):
                        let sgn: Double = S[i].2 >= 0 ? 1 : -1
                        A3 = (x, y, out.map { sgn * $0 } ?? H.2)
                    default:
                        A3 = pt(legs[i][3])
                    }
                    let a = pr(H), b = pr(A3), d = (a.2 + b.2) / 2
                    if im.t == "cable" {
                        items.append(FormOp(kind: .line, pts: [cg(a), cg(b)], width: 0.7, role: .cable, depth: d - 0.5))
                        items.append(FormOp(kind: .circle, center: cg(b), rx: 1.4, ry: 1.4, role: .steel, depth: b.2))
                        items.append(FormOp(kind: .circle, center: cg(a), rx: 1.5, ry: 1.5, role: .accent, depth: a.2 + 0.02))
                    } else {
                        items.append(FormOp(kind: .line, pts: [cg(a), cg(b)], width: 1.1, role: .band, dashed: true, depth: d))
                    }
                }
            case "handle":
                for (H, _) in hands {
                    let a = pr(H)
                    items.append(FormOp(kind: .circle, center: cg(a), rx: 1.7, ry: 1.7, role: .accent, depth: a.2 + 0.02))
                }
            case "pad":
                let idx = im.at == "ankle" ? [legs[0][2], legs[1][2]] : [arms[0][0], arms[1][0]]
                let P0 = pt(idx[0]), P1 = pt(idx[1])
                let u = norm((P0.0 - P1.0, P0.1 - P1.1, P0.2 - P1.2))
                let a = pr(add(P0, u, 3)), b = pr(add(P1, u, -3))
                items.append(FormOp(kind: .line, pts: [cg(a), cg(b)], width: 4.4, role: .pad, depth: (a.2 + b.2) / 2 + 0.5))
            case "pedal":
                for l in legs {
                    let a = pr(add(pt(l[2]), (-3.0, -2.2, 0.0)))
                    let b = pr(add(pt(l[3]), (1.5, -1.6, 0.0)))
                    items.append(FormOp(kind: .line, pts: [cg(a), cg(b)], width: 2.2, role: .steel, depth: (a.2 + b.2) / 2 - 0.3))
                }
            case "sled":
                let A0 = pt(legs[0][2]), T0 = pt(legs[0][3]), A1 = pt(legs[1][2]), T1 = pt(legs[1][3])
                let m = mid([A0, T0, A1, T1])
                let u = norm((T0.0 - A0.0, T0.1 - A0.1, T0.2 - A0.2))
                let corners: [(Double, Double)] = [(-8, -9), (8, -9), (8, 9), (-8, 9)]
                let q = corners.map { pr(add(add(m, u, $0.0), (0, 0, $0.1))) }
                items.append(FormOp(kind: .poly, pts: q.map(cg), width: 1, role: .propFill, stroke: .steel,
                                    depth: avgDepth(q) - 3))
            default:
                break
            }
        }

        props.sort { $0.depth < $1.depth }
        items.sort { $0.depth < $1.depth }
        let groundLine = FormOp(kind: .line, pts: [CGPoint(x: 2, y: ground), CGPoint(x: 98, y: ground)], width: 1, role: .ground, depth: -999)
        return [groundLine] + props + items
    }

    static func hull(_ input: [CGPoint]) -> [CGPoint] {
        func snap(_ v: CGFloat) -> CGFloat {
            let scaled: CGFloat = (v * 1000).rounded()
            return scaled / 1000
        }
        var pts: [CGPoint] = []
        for p in input { pts.append(CGPoint(x: snap(p.x), y: snap(p.y))) }
        pts.sort { (a: CGPoint, b: CGPoint) -> Bool in
            if a.x == b.x { return a.y < b.y }
            return a.x < b.x
        }
        var unique: [CGPoint] = []
        for p in pts where unique.last != p { unique.append(p) }
        guard unique.count > 2 else { return unique }
        func cross(_ o: CGPoint, _ a: CGPoint, _ b: CGPoint) -> CGFloat { (a.x - o.x) * (b.y - o.y) - (a.y - o.y) * (b.x - o.x) }
        var lower: [CGPoint] = [], upper: [CGPoint] = []
        for p in unique {
            while lower.count >= 2 && cross(lower[lower.count - 2], lower[lower.count - 1], p) <= 0 { lower.removeLast() }
            lower.append(p)
        }
        for p in unique.reversed() {
            while upper.count >= 2 && cross(upper[upper.count - 2], upper[upper.count - 1], p) <= 0 { upper.removeLast() }
            upper.append(p)
        }
        return Array(lower.dropLast()) + Array(upper.dropLast())
    }
}

// MARK: - View

struct FormPalette {
    var ink: Color = ForgeColors.abhiMode ? ForgeColors.ink : .primary
    var accent: Color = ForgeColors.accent
    var background: Color = Color(white: 0.5).opacity(0.0)
    var face: Color = .white

    func color(_ role: FormRole) -> Color {
        switch role {
        case .ink: return ink
        case .accent, .plate, .band: return accent
        case .steel: return Color.gray
        case .prop: return Color.gray.opacity(0.55)
        case .propFill: return Color.gray.opacity(0.22)
        case .cable: return Color.gray.opacity(0.7)
        case .pad: return accent.opacity(0.55)
        case .ground: return Color.gray.opacity(0.35)
        case .face: return face
        }
    }
}

/// An animated figure doing the exercise. `yaw` is in degrees: 90 = side, 0 = front, 180 = back.
struct FormFigureView: View {
    let exerciseID: String
    var yaw: Double? = nil
    var spin = false
    var animating = true
    var palette = FormPalette()

    var body: some View {
        if let lib = FormLibrary.shared, let ex = lib.exercises[FormLibrary.key(exerciseID)], let pat = lib.patterns[ex.p] {
            TimelineView(.animation(minimumInterval: 1.0 / 30.0, paused: !animating)) { context in
                let time = context.date.timeIntervalSinceReferenceDate
                let baseYaw = yaw ?? pat.defaultYaw
                let currentYaw = spin ? baseYaw + time.truncatingRemainder(dividingBy: 9) * 40 : baseYaw
                Canvas { ctx, size in
                    let frame = pat.frame(at: animating ? pat.phase(time) : 0.5)
                    let ops = FormScene.ops(pattern: pat, exercise: ex, frame: frame, yaw: currentYaw * .pi / 180,
                                            ground: lib.ground, headRadius: lib.head)
                    FormFigureView.draw(ops, in: &ctx, size: size, palette: palette)
                }
            }
            .aspectRatio(1, contentMode: .fit)
        } else {
            Image(systemName: "figure.strengthtraining.traditional")
                .resizable().scaledToFit().padding(12).foregroundStyle(.secondary)
                .aspectRatio(1, contentMode: .fit)
        }
    }

    static func draw(_ ops: [FormOp], in ctx: inout GraphicsContext, size: CGSize, palette: FormPalette) {
        let side: CGFloat = Swift.min(size.width, size.height)
        let pad: CGFloat = side * 0.04
        let k: CGFloat = (side - pad * 2) / 100
        let ox: CGFloat = (size.width - side) / 2 + pad
        let oy: CGFloat = (size.height - side) / 2 + pad
        func X(_ p: CGPoint) -> CGPoint {
            let x: CGFloat = ox + p.x * k
            let y: CGFloat = oy + (100 - p.y) * k
            return CGPoint(x: x, y: y)
        }
        for op in ops {
            let color = palette.color(op.role).opacity(op.alpha)
            let lineWidth: CGFloat = Swift.max(1, CGFloat(op.width) * k)
            switch op.kind {
            case .line:
                guard let first = op.pts.first else { continue }
                var path = Path()
                path.move(to: X(first))
                for p in op.pts.dropFirst() { path.addLine(to: X(p)) }
                let style: StrokeStyle
                if op.dashed {
                    style = StrokeStyle(lineWidth: lineWidth, lineCap: .round, lineJoin: .round, dash: [2.4 * k, 1.8 * k])
                } else {
                    style = StrokeStyle(lineWidth: lineWidth, lineCap: .round, lineJoin: .round)
                }
                ctx.stroke(path, with: .color(color), style: style)
            case .circle:
                let c = X(op.center)
                let rx: CGFloat = CGFloat(op.rx) * k
                let ry: CGFloat = CGFloat(op.ry) * k
                let rect = CGRect(x: c.x - rx, y: c.y - ry, width: rx * 2, height: ry * 2)
                ctx.fill(Path(ellipseIn: rect), with: .color(color))
            case .poly:
                guard let first = op.pts.first else { continue }
                var path = Path()
                path.move(to: X(first))
                for p in op.pts.dropFirst() { path.addLine(to: X(p)) }
                if op.pts.count >= 3 {
                    path.closeSubpath()
                    ctx.fill(path, with: .color(color))
                }
                ctx.stroke(path, with: .color(palette.color(op.stroke)), style: StrokeStyle(lineWidth: lineWidth, lineJoin: .round))
            }
        }
    }
}

/// Side / Front / Back / Turn picker shared by iPhone and Watch.
enum FormAngle: String, CaseIterable, Identifiable {
    case side, front, back, turn
    var id: String { rawValue }
    var label: String { rawValue.capitalized }
    var yaw: Double {
        switch self {
        case .side, .turn: return 90
        case .front: return 0
        case .back: return 180
        }
    }
}

/// App-wide accent colours. "Abhi mode" switches everything to purple.
enum ForgeColors {
    static var abhiMode: Bool = UserDefaults.standard.bool(forKey: "forge.abhiMode")

    static let orange = Color(red: 0.89, green: 0.35, blue: 0.12)
    static let purple = Color(red: 0.55, green: 0.27, blue: 0.93)

    static var accent: Color { abhiMode ? purple : orange }

    // Abhi mode replaces black/dark surfaces and text with purples.
    /// Light purple page background.
    static let lavender = Color(red: 0.93, green: 0.89, blue: 1.0)
    /// Deep purple used instead of black for text and figures.
    static let ink = Color(red: 0.24, green: 0.12, blue: 0.40)
    /// Watch background (the Watch is always dark, so a mid purple keeps white text readable).
    static let watchBackground = LinearGradient(colors: [Color(red: 0.42, green: 0.25, blue: 0.68), Color(red: 0.22, green: 0.12, blue: 0.38)],
                                                startPoint: .top, endPoint: .bottom)
    /// Used where the app would otherwise show green for "good".
    static var positive: Color { abhiMode ? Color(red: 0.70, green: 0.45, blue: 1.0) : .green }

    static func setAbhiMode(_ on: Bool) {
        abhiMode = on
        UserDefaults.standard.set(on, forKey: "forge.abhiMode")
    }
}
